site_name: 龙芯云
theme:
    favicon: images/favicon.svg
    name: material
    language: zh
    palette:
      primary: red
    features:
        - content.action.edit
        - content.action.view
        - navigation.instant
        - navigation.tracking
        - navigation.tabs
        - navigation.top
        # - navigation.sections
        - navigation.indexes
        # - navigation.expand
        - content.code.copy
        - content.code.annotate

repo_name: Loongson-Cloud-Community
repo_url: https://github.com/Loongson-Cloud-Community/Loongson-Cloud-Community
edit_uri: edit/main/docs

markdown_extensions:
  - admonition  # 警告标签
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
