site_name: 龙芯云
theme:
    favicon: images/favicon.svg
    name: material
    language: zh
    palette:
      primary: red
    features:
        - content.action.edit
        - content.action.view
        - navigation.instant
        - navigation.tracking
        - navigation.tabs
        # - navigation.sections
        - navigation.indexes
        # - navigation.expand

repo_name: Loongson-Cloud-Community
repo_url: https://github.com/Loongson-Cloud-Community/Loongson-Cloud-Community
edit_uri: edit/main/docs

